const RESOURCE_ENTITY_TYPES = Object.freeze([
  'workspace',
  'collection',
  'folder',
  'request-group',
  'request',
  'environment',
  'script',
  'mock-rule',
]);

const RUNTIME_TABLES = Object.freeze([
  'captured_requests',
  'execution_histories',
  'execution_results',
  'test_results',
]);

const STORAGE_SCHEMA_VERSION = 1;
const RESOURCE_MANIFEST_SCHEMA_VERSION = 1;
const RUNTIME_SCHEMA_VERSION = 1;
const RUNTIME_METADATA_SCHEMA_VERSION = 1;
const COLLECTION_RESOURCE_SCHEMA_VERSION = 1;
const REQUEST_GROUP_RESOURCE_SCHEMA_VERSION = 1;
const REQUEST_RESOURCE_SCHEMA_VERSION = 2;
const ENVIRONMENT_RESOURCE_SCHEMA_VERSION = 1;
const SCRIPT_RESOURCE_SCHEMA_VERSION = 1;
const MOCK_RULE_RESOURCE_SCHEMA_VERSION = 1;
const AUTHORED_RESOURCE_BUNDLE_SCHEMA_VERSION = 3;
const AUTHORED_RESOURCE_BUNDLE_KIND = 'local-request-inspector-authored-resource-bundle';
const RESOURCE_STORAGE_KIND = 'json-files';
const RUNTIME_STORAGE_KIND = 'sqlite';
const RUNTIME_PERSISTENCE_POLICY = 'redacted-only';
const RUNTIME_REQUEST_SNAPSHOT_SCHEMA_VERSION = 1;
const RUNTIME_CAPTURE_SUMMARY_SCHEMA_VERSION = 1;
const STORAGE_COMPATIBILITY_STATES = Object.freeze({
  READ_COMPATIBLE: 'read-compatible',
  BOOTSTRAP_RECOVERABLE: 'bootstrap-recoverable',
  MIGRATION_NEEDED: 'migration-needed',
  UNSUPPORTED_VERSION: 'unsupported-version',
  MALFORMED_DATA: 'malformed-data',
});
const RESOURCE_RECORD_KINDS = Object.freeze({
  COLLECTION: 'collection',
  REQUEST_GROUP: 'request-group',
  REQUEST: 'request',
  ENVIRONMENT: 'environment',
  SCRIPT: 'script',
  MOCK_RULE: 'mock-rule',
});

module.exports = {
  RESOURCE_ENTITY_TYPES,
  RUNTIME_TABLES,
  STORAGE_SCHEMA_VERSION,
  RESOURCE_MANIFEST_SCHEMA_VERSION,
  RUNTIME_SCHEMA_VERSION,
  RUNTIME_METADATA_SCHEMA_VERSION,
  COLLECTION_RESOURCE_SCHEMA_VERSION,
  REQUEST_GROUP_RESOURCE_SCHEMA_VERSION,
  REQUEST_RESOURCE_SCHEMA_VERSION,
  ENVIRONMENT_RESOURCE_SCHEMA_VERSION,
  SCRIPT_RESOURCE_SCHEMA_VERSION,
  MOCK_RULE_RESOURCE_SCHEMA_VERSION,
  AUTHORED_RESOURCE_BUNDLE_SCHEMA_VERSION,
  AUTHORED_RESOURCE_BUNDLE_KIND,
  RESOURCE_STORAGE_KIND,
  RUNTIME_STORAGE_KIND,
  RUNTIME_PERSISTENCE_POLICY,
  RUNTIME_REQUEST_SNAPSHOT_SCHEMA_VERSION,
  RUNTIME_CAPTURE_SUMMARY_SCHEMA_VERSION,
  STORAGE_COMPATIBILITY_STATES,
  RESOURCE_RECORD_KINDS,
};

